# Generated by Django 6.1 on 2026-08-20 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('transcribed', 'Transcribed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioTranscription',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_content', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='api.audio')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionContent',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('clean', 'Clean transcription'), ('summary', 'Summary'), ('notes', 'Notes'), ('article', 'Article'), ('interview', 'Interview'), ('custom', 'Custom')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.audiotranscription')),
            ],
        ),
    ]
