# Generated by Django 6.1 on 2026-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='source_path',
            field=models.CharField(blank=True, editable=False, max_length=4096, null=True, unique=True),
        ),
    ]
