# Generated by Django 6.1 on 2026-09-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audio_source_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='progress_done',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='progress_total',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
